# This action is based on Github's default starter workflow for Python at
# https://github.com/actions/starter-workflows/blob/master/ci/python-package.yml
# (C) Github, MIT License

name: Python package

on:
  push:
    branches:
      - '*'  # Activate on all branches
    paths-ignore:
      - 'README.md'
      - 'test.txt'
      
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'image.png'
      - '.spyproject'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]

    - name: Lint with Ruff
      run: |
        ruff check my_awesome_project

    - name: Lint with PyLint
      run: |
        pylint my_awesome_project


    - name: Lint with PyLint
      run: |
        pylint mlutils

    - name: Check types with MyPy
      run: |
          mypy mlutils

    - name: Test with pytest
      run: |
        pytest tests