name: Generate Example YAML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_yaml:
    if: "!startsWith(github.event.head_commit.message, '[auto]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone VISNet-framework/mlutils with token
        env:
          GITHUB_TOKEN: ${{ secrets.MLUTILS_TOKEN }}
        run: |
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/VISNet-framework/mlutils.git
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd mlutils
          python -m pip install --upgrade pip
          pip install .[test]

      - name: Run generate_example_yaml in the root directory
        run: |
          cd mlutils
          python -c "from tests.mlutils.test_config import generate_example_yaml; from mlutils.config import MainConfig; generate_example_yaml(MainConfig, '../example_config.yaml')"
      - name: Commit and push example_config.yaml
        env:
          GH_PUSH_TOKEN: ${{ secrets.DOCS_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add example_config.yaml
          git commit -m "[auto] Update example_config.yaml" || echo "No changes to commit"
          git push https://x-access-token:${GH_PUSH_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
