name: Generate Example YAML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone VISNet-framework/mlutils with token
        env:
          GITHUB_TOKEN: ${{ secrets.MLUTILS_TOKEN }}
        run: |
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/VISNet-framework/mlutils.git
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd mlutils
          python -m pip install --upgrade pip
          pip install .[test]

      - name: Run generate_example_yaml
        run: |
          cd mlutils
          python -c "from tests.mlutils.test_config import generate_example_yaml; from mlutils.config import MainConfig; generate_example_yaml(MainConfig, 'example_config.yaml')"

      - name: Upload example_config.yaml as artifact
        uses: actions/upload-artifact@v4
        with:
          name: example_config
          path: example_config.yaml
